### ISSUE TITLE
Change name of repo?

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/burping-jelly-baby#13]
I was going to change the name of the repo to burping-jellybaby. Thoughts @bennuttall?

**Comment by lurch** [comment]
Apologies if I'm intruding, but it seems there's still a few places in worksheet.md (and README.md) that refer to 'scream' rather than 'burp'.
Looking through the commits, I'm guessing this change was made so that the worksheet could be followed on Pis that don't have an internet connection?
I guess the two references to "download" in worksheet.md need to be changed too.

And maybe I'm just being too pedantic, but perhaps "Make a copy of Sonic Pi's sound samples folder ..." should be changed to "Make a copy of one of Sonic Pi's sound samples ..."

**Comment by MissPhilbin** [comment]
Thanks @lurch 

We are in the process of moving our resources into a new template and updating them. These types of errors would have been picked up in the copy edit stage, but I've corrected them anyway.

**Comment by LornaLynch** [comment]
If @MissPhilbin doesn't have any objection, I can change the name of the repo to Burping Jelly Baby, and make the necessary changes in the text.

**Comment by bennuttall** [comment]
Yes, can do. Although the cover may need updating by @samalderhyde?

Also if we change the name of the repo, the URL will change so we'll need to update links and redirect accordingly.

**Comment by LornaLynch** [comment]
Alternatively, could we just have a scream instead of a burp for download? If there's an appropriate sound file available, we could keep the links etc as they are, and just update this worksheet?

**Comment by bennuttall** [comment]
It was scream originally. I think there was a conscious decision to change it to burp, for pedagogical reasons or something.

**Comment by samalderhyde** [comment]
I can change the cover sure, shall I go ahead?

**Comment by bennuttall** [comment]
Yeah make it burp, dude

**Comment by samalderhyde** [comment]
yesssss

**Comment by LornaLynch** [comment]
Ah, yes: it seems there's already a well-known chemistry experiment called The Screaming Jelly Baby, which involves pouring potassium chlorate on sweets. Moving to burp-mode.

**Comment by bennuttall** [comment]
Ok I have a burp cover from @samalderhyde.

I see the repo name has been changed - this means it will no longer be updated on the server as the [list of live resources](https://github.com/raspberrypilearning/live-resources/blob/master/resources.txt) contains `screaming-jellybaby`

I'll go change it now and update the link in WordPress.

**Comment by bennuttall** [comment]
I'll also need to add a redirect in for anyone browsing to raspberrypi.org/learning/screaming-jellybaby

**Comment by LornaLynch** [comment]
Thanks, Ben: sorry, I emailed you about this, as I couldn't see how to update the link myself.

**Comment by LornaLynch** [comment]
I won't mess around with the list of live resources while you're doing stuff, but if you have a moment could you let me know what I need to do if this sort of situation arises again?

**Comment by bennuttall** [comment]
Ok I recently implemented the redirect rules but missed the not-hyphenated `jellybaby`. Will add and we can close this issue.

**Comment by lurch** [comment]
For the sake of tidiness, is it worth deleting the now-unused `sounds` folder from this repo?
