### ISSUE TITLE
Missing image in worksheet

### ISSUE THREAD

**Issue by helenlynn** [raspberrypilearning/burping-jelly-baby#17]
`worksheet.md` reads:

>The picture above shows the Raspberry Pi GPIO header pins; the diagram above the pins shows the pin numbers

but there's no picture, only the pinout diagram.

**Comment by bennuttall** [comment]
Thanks. Should probably be changed.

FYI it's useful to link to files like this:

```
[worksheet.md](https://github.com/raspberrypilearning/burping-jelly-baby/blob/master/worksheet.md)
```

i.e. [worksheet.md](https://github.com/raspberrypilearning/burping-jelly-baby/blob/master/worksheet.md)

**Comment by helenlynn** [comment]
Thanks. Noted.
