### ISSUE TITLE
copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/burping-jelly-baby#18]
Hi @LornaLynch and @lauraclay.
I've updated this resource in the usual fashion. There's quite a few changes so not really worth looking at the diffs. The worksheet is at https://github.com/raspberrypilearning/burping-jelly-baby/blob/update/worksheet.md

Could I get a copy edit at some point - no rush.

Cheers

**Comment by LornaLynch** [comment]
I can have a look this evening of that's ok?

**Comment by MarcScott** [comment]
Perfect, thanks.

**Comment by LornaLynch** [comment]
Hi guys: sorry, but the kids took over and I haven't had a chance to get to this. @lauraclay, if you are working tomorrow, and you are at a loss, do have at it. Otherwise I will get to it ASAP.

**Comment by MarcScott** [comment]
Not a worry. Whenever you get a chance is fine.
Thanks

**Comment by bennuttall** [comment]
@MarcScott Note @MissPhilbin just made a small change in c66c7c2bae335f4479ece39896e00bbaf8d3e580 to fix an issue with the sound file, can you copy those changes into this branch then when it's copy edited it can go live.

**Comment by MarcScott** [comment]
@lauraclay Can I close this now? I see you were working on it.

**Comment by lauraclay** [comment]
@MarcScott I was working on the update branch but yes, that's done if you want to add it in.

**Comment by MarcScott** [comment]
K Thanks.
