### ISSUE TITLE
burp.wav sound file not found by script

### ISSUE THREAD

**Issue by DeeJay** [raspberrypilearning/burping-jelly-baby#23]
The sample sound file is downloaded to /home/pi/jellybaby/burp.wav

The burp.py script is created in /home/pi/burp.py

The statement `burp = pygame.mixer.Sound("burp.wav")`  therefore fails because the sound file is not in the current working directory.

Could be solved in one of a number of ways -

* Create the script in /home/pi/jellybaby/burp.py
or
* Download the .wav file to /home/pi
or
* Specify the full file path in pygame.mixer.Sound( )

**Comment by DougieLawson** [comment]
Or make a symlink between /home/pi/jellybaby/burp.wav and /home/pi/burp.wav.

```cd ~/pi; ln -s /home/pi/jellybaby/burp.wav```

**Comment by lawsie** [comment]
Thanks @DeeJay - I've put in a PR to clarify this.
https://github.com/raspberrypilearning/burping-jelly-baby/pull/25
